import img1 from "../../../images/headset-earbuds-transparent.jpg";

export const AllProductsData = [
  {
    id: 1,
    category: "delivered",
    img: img1,
    orderNumber: "yN0123",
    orderOn: "jan 26, 2023",
    orderDelivered: "jan 26, 2023",
    btnName: "delivered",
    productName: "tuddrom m01 black",
    productColor: "black",
    Qty: "1",
    Rs: "749",
    paidBy: "",
  },
  {
    id: 2,
    category: "processing",
    img: img1,
    orderNumber: "yN0123",
    orderOn: "jan 26, 2023",
    orderDelivered: "jan 26, 2023",
    btnName: "processing",
    productName: "tuddrom m01 black",
    productColor: "black",
    Qty: "1",
    Rs: "749",
    paidBy: "",
  },
  {
    id: 3,
    category: "canceled",
    img: img1,
    orderNumber: "yN0123",
    orderOn: "jan 26, 2023",
    orderDelivered: "jan 26, 2023",
    btnName: "canceled",
    productName: "tuddrom m01 black",
    productColor: "black",
    Qty: "1",
    Rs: "749",
    paidBy: "",
  },
  {
    id: 4,
    category: "returned",
    img: img1,
    orderNumber: "yN0123",
    orderOn: "jan 26, 2023",
    orderDelivered: "jan 26, 2023",
    btnName: "returned",
    productName: "tuddrom m01 black",
    productColor: "black",
    Qty: "1",
    Rs: "749",
    paidBy: "",
  },
];
